// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mephvrrrzjzvvtauqlyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lcGh2cnJyemp6dnZ0YXVxbHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNjg2OTYsImV4cCI6MjA4Njk0NDY5Nn0.y-yRxJLgiSWvLmHSLt_YoA30jWlEkUgnu556w0on4HQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});